---
# tasks file for SSITA_geocitizen_DB

- include_tasks: preset.yaml
- include_tasks: preset_postgresql.yaml
- include_tasks: geocitizen.yaml
- include_tasks: afterset_postgresql.yaml

- name: save IP of DB to temp local file
  copy: 
    content: "{{ host_private }}" 
    dest: /tmp/varfile
    mode: 0664
  delegate_to: 127.0.0.1

...
